name: Project Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'project/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r project/dependencies.txt
  
      - name: Run the project file
        run: |
          chmod +x ./project/test.sh
          ./project/test.sh
        
